stages:
  - build
  - test
  - link

cache: 
  paths:
    - vendor
    - node_modules
    - .env

before_script:
  - echo "Before script"
  - cd /nginx/project
building:
  stage: build
  tags: 
    - museums
  script:
    - composer install
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate:fresh --seed
  rules:
    - if: $CI_COMMIT_BRANCH == 'production'
testing:
  stage: test
  tags:
    - museums
  script:
    - php ./vendor/bin/phpunit

linking:
  stage: link
  allow_failure: true
  tags:
    - museums
  script:
    - rm C:\nginx\project
    - New-Item -Path C:\nginx\project\ -ItemType SymbolicLink -Value .
    - rm C:\nginx\project\public\storage
    - New-Item -Path C:\nginx\project\public\storage\ -ItemType SymbolicLink -Value .\storage\app\public
  rules:
    - if: $CI_COMMIT_BRANCH == 'production'